// @generated by protobuf-ts 2.11.1 with parameter output_javascript
// @generated from protobuf file "pbf/transfers/api.proto" (package "transfers", syntax proto3)
// tslint:disable
/**
 * @generated ServiceType for protobuf service transfers.API
 */
export declare const API: any;
