// @generated by protobuf-ts 2.11.1 with parameter output_javascript
// @generated from protobuf file "pbf/transfers/api.proto" (package "transfers", syntax proto3)
// tslint:disable
// @generated by protobuf-ts 2.11.1 with parameter output_javascript
// @generated from protobuf file "pbf/transfers/api.proto" (package "transfers", syntax proto3)
// tslint:disable
import { SearchO } from "./search";
import { SearchI } from "./search";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service transfers.API
 */
export const API = new ServiceType("transfers.API", [
    { name: "Search", options: {}, I: SearchI, O: SearchO }
]);
