// @generated by protobuf-ts 2.11.1 with parameter output_javascript
// @generated from protobuf file "pbf/transfers/api.proto" (package "transfers", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import type { SearchO } from "./search";
import type { SearchI } from "./search";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service transfers.API
 */
export interface IAPIClient {
  /**
   * @generated from protobuf rpc: Search
   */
  search(input: SearchI, options?: RpcOptions): UnaryCall<SearchI, SearchO>;
}
/**
 * @generated from protobuf service transfers.API
 */
export declare class APIClient implements IAPIClient, ServiceInfo {
  private readonly _transport;
  typeName: any;
  methods: any;
  options: any;
  constructor(_transport: RpcTransport);
  /**
   * @generated from protobuf rpc: Search
   */
  search(input: SearchI, options?: RpcOptions): UnaryCall<SearchI, SearchO>;
}
