// @generated by protobuf-ts 2.11.1 with parameter output_javascript
// @generated from protobuf file "pbf/transfers/search.proto" (package "transfers", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * SearchI is the input for searching transfers.
 *
 *     {
 *         "filter": {
 *             "paging": {
 *                 "kind": "page",
 *                 "start": "0",
 *                 "stop": "49"
 *             }
 *         },
 *         "search": [
 *             {
 *                 "address": "0x4838...5f97"
 *             }
 *         ]
 *     }
 *
 *
 * @generated from protobuf message transfers.SearchI
 */
export interface SearchI {
  /**
   * @generated from protobuf field: transfers.SearchI_Filter filter = 100
   */
  filter?: SearchI_Filter;
  /**
   * @generated from protobuf field: repeated transfers.SearchI_Object search = 200
   */
  search: SearchI_Object[];
}
/**
 * @generated from protobuf message transfers.SearchI_Filter
 */
export interface SearchI_Filter {
  /**
   * @generated from protobuf field: transfers.SearchI_Filter_Paging paging = 100
   */
  paging?: SearchI_Filter_Paging;
}
/**
 * @generated from protobuf message transfers.SearchI_Filter_Paging
 */
export interface SearchI_Filter_Paging {
  /**
   * @generated from protobuf field: string kind = 100
   */
  kind: string;
  /**
   * @generated from protobuf field: string start = 200
   */
  start: string;
  /**
   * @generated from protobuf field: string stop = 300
   */
  stop: string;
}
/**
 * @generated from protobuf message transfers.SearchI_Object
 */
export interface SearchI_Object {
  /**
   * address is the wallet address for which transfers are searched.
   *
   * @generated from protobuf field: string address = 100
   */
  address: string;
}
/**
 * SearchO is the output for searching transfers.
 *
 *     {
 *         "result": [
 *             {
 *                 "address": "0x4838...5f97",
 *                 "transfers": [
 *                     {
 *                         "amount": "420000000000000000000",
 *                         "created_at": "1689001255",
 *                         "id": "a9526eca-953e-49f7-aa4c-12fc06132124",
 *                         "to": "0x4838...5f97"
 *                     }
 *                 ]
 *             }
 *         ]
 *     }
 *
 *
 * @generated from protobuf message transfers.SearchO
 */
export interface SearchO {
  /**
   * @generated from protobuf field: repeated transfers.SearchO_Object result = 100
   */
  result: SearchO_Object[];
}
/**
 * @generated from protobuf message transfers.SearchO_Object
 */
export interface SearchO_Object {
  /**
   * address is the wallet address for which transfers are searched.
   *
   * @generated from protobuf field: string address = 100
   */
  address: string;
  /**
   * transfers is the list of transfers associated to the given wallet address.
   *
   * @generated from protobuf field: repeated transfers.SearchO_Object_Transfer transfers = 200
   */
  transfers: SearchO_Object_Transfer[];
}
/**
 * @generated from protobuf message transfers.SearchO_Object_Transfer
 */
export interface SearchO_Object_Transfer {
  /**
   * amount is the bigint value of the onchain transfer. It is the caller's
   * responsibility to know the number of decimals for any given token transfer.
   *
   * @generated from protobuf field: string amount = 100
   */
  amount: string;
  /**
   * created_at is the unix timestamp in seconds at which this transfer got
   * created.
   *
   * @generated from protobuf field: string created_at = 200
   */
  createdAt: string;
  /**
   * id is the UUID of the given transfer object.
   *
   * @generated from protobuf field: string id = 300
   */
  id: string;
  /**
   * to is the to field of this transfer, the wallet address to which tokens
   * have been sent.
   *
   * @generated from protobuf field: string to = 400
   */
  to: string;
}
declare class SearchI$Type extends MessageType<SearchI> {
  constructor();
  create(value?: PartialMessage<SearchI>): SearchI;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: SearchI,
  ): SearchI;
  internalBinaryWrite(
    message: SearchI,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message transfers.SearchI
 */
export declare const SearchI: SearchI$Type;
declare class SearchI_Filter$Type extends MessageType<SearchI_Filter> {
  constructor();
  create(value?: PartialMessage<SearchI_Filter>): SearchI_Filter;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: SearchI_Filter,
  ): SearchI_Filter;
  internalBinaryWrite(
    message: SearchI_Filter,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message transfers.SearchI_Filter
 */
export declare const SearchI_Filter: SearchI_Filter$Type;
declare class SearchI_Filter_Paging$Type extends MessageType<SearchI_Filter_Paging> {
  constructor();
  create(value?: PartialMessage<SearchI_Filter_Paging>): SearchI_Filter_Paging;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: SearchI_Filter_Paging,
  ): SearchI_Filter_Paging;
  internalBinaryWrite(
    message: SearchI_Filter_Paging,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message transfers.SearchI_Filter_Paging
 */
export declare const SearchI_Filter_Paging: SearchI_Filter_Paging$Type;
declare class SearchI_Object$Type extends MessageType<SearchI_Object> {
  constructor();
  create(value?: PartialMessage<SearchI_Object>): SearchI_Object;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: SearchI_Object,
  ): SearchI_Object;
  internalBinaryWrite(
    message: SearchI_Object,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message transfers.SearchI_Object
 */
export declare const SearchI_Object: SearchI_Object$Type;
declare class SearchO$Type extends MessageType<SearchO> {
  constructor();
  create(value?: PartialMessage<SearchO>): SearchO;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: SearchO,
  ): SearchO;
  internalBinaryWrite(
    message: SearchO,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message transfers.SearchO
 */
export declare const SearchO: SearchO$Type;
declare class SearchO_Object$Type extends MessageType<SearchO_Object> {
  constructor();
  create(value?: PartialMessage<SearchO_Object>): SearchO_Object;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: SearchO_Object,
  ): SearchO_Object;
  internalBinaryWrite(
    message: SearchO_Object,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message transfers.SearchO_Object
 */
export declare const SearchO_Object: SearchO_Object$Type;
declare class SearchO_Object_Transfer$Type extends MessageType<SearchO_Object_Transfer> {
  constructor();
  create(
    value?: PartialMessage<SearchO_Object_Transfer>,
  ): SearchO_Object_Transfer;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: SearchO_Object_Transfer,
  ): SearchO_Object_Transfer;
  internalBinaryWrite(
    message: SearchO_Object_Transfer,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message transfers.SearchO_Object_Transfer
 */
export declare const SearchO_Object_Transfer: SearchO_Object_Transfer$Type;
export {};
